<?xml version="1.0" encoding="UTF-8"?>
<!-- Generated by org.testng.reporters.JUnitXMLReporter -->
<testsuite ignored="0" hostname="NithinThantry" failures="2" tests="5" name="TestNG" time="0.125" errors="0" timestamp="2022-12-09T08:00:56 IST">
  <testcase classname="testNg.annotation.MyTestOne" name="testone" time="0.019">
    <skipped/>
  </testcase> <!-- testone -->
  <testcase classname="testNg.annotation.MyTestOne" name="testone" time="0.003">
    <skipped/>
  </testcase> <!-- testone -->
  <testcase classname="testNg.annotation.MyTestOne" name="testone" time="0.003">
    <skipped/>
  </testcase> <!-- testone -->
  <testcase classname="testNg.annotation.MyTestOne" name="testone" time="0.003">
    <failure type="java.lang.AssertionError" message="expected [true] but found [false]">
      <![CDATA[java.lang.AssertionError: expected [true] but found [false]
at testNg.annotation.MyTestOne.testone(MyTestOne.java:11)
at java.base/java.util.ArrayList.forEach(ArrayList.java:1541)
... Removed 33 stack frames]]>
    </failure>
  </testcase> <!-- testone -->
  <testcase classname="testNg.annotation.MyTestOne" name="testwo" time="0.003">
    <failure type="java.lang.AssertionError" message="expected [true] but found [false]">
      <![CDATA[java.lang.AssertionError: expected [true] but found [false]
at testNg.annotation.MyTestOne.testwo(MyTestOne.java:17)
at java.base/java.util.ArrayList.forEach(ArrayList.java:1541)
... Removed 33 stack frames]]>
    </failure>
  </testcase> <!-- testwo -->
</testsuite> <!-- TestNG -->
